services:
  # Service definition for our FastAPI application
  fastapi_app:
    # Build the Docker image from the Dockerfile in the current directory (.)
    build: .
    container_name: mqtt_validation_app
    ports:
      # Map port 8000 on the host machine to port 8000 in the container
      - "8000:8000"
    volumes:
      # Mount the current directory on the host to /app in the container
      # This allows code changes on the host to be immediately reflected
      # inside the container, enabling live reloading.
      - .:/app
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-token
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=mqtt_data
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=mqtt_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - fastapi_app

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - influxdb

volumes:
  influxdb_data:
  grafana_data: 