global:
  scrape_interval: 5s #  scrape targets every 5 seconds.

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'fastapi_app_metrics'
    # metrics_path defaults to '/metrics'
    static_configs:
      # This is the target to scrape. We use the service name defined in docker-compose.yml,

      - targets: ['fastapi_app:8000'] 

